# Generated by Django 3.2.9 on 2021-11-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(blank=True, max_length=20, null=True)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('company_about', models.CharField(blank=True, max_length=5000, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_banner', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('job_about', models.CharField(blank=True, max_length=2000, null=True)),
                ('job_skills', models.CharField(blank=True, max_length=500, null=True)),
                ('job_locations', models.CharField(blank=True, max_length=500, null=True)),
                ('job_vacancies', models.CharField(blank=True, max_length=10, null=True)),
                ('job_qualification_required', models.CharField(blank=True, max_length=100, null=True)),
                ('job_posted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_profiles', to='company_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAppBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit_image', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
            ],
        ),
    ]
