# Generated by Django 3.2.9 on 2021-11-16 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyappjobs',
            name='job_posted_date',
        ),
        migrations.AddField(
            model_name='companyappjobs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 16, 2, 53, 54, 71930, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyappjobs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
