# Generated by Django 3.2.9 on 2021-11-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_auto_20211116_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyAppJobs',
            new_name='Jobs',
        ),
    ]
